# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='class_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='gender',
            field=models.IntegerField(default=1),
        ),
    ]
