# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180325_0329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='Students',
        ),
    ]
