# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180325_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='authority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='display',
            field=models.IntegerField(default=0),
        ),
    ]
